### ISSUE TITLE
Some bug

### ISSUE THREAD

**Issue by qwerty472123** [Ten0/updatable_priority_queue#3]
In the `set` function:

https://github.com/Ten0/updatable_priority_queue/blob/536e8733940471c1a460de62ce57986d302abefb/updatable_priority_queue.h#L59

Notice that `id_to_heappos` is unsigned. So, `id_to_heappos[key] >= 0` should be changed to `heappos < ((size_t)-2)`.

In the `pop` and `pop_value` function:

https://github.com/Ten0/updatable_priority_queue/blob/536e8733940471c1a460de62ce57986d302abefb/updatable_priority_queue.h#L39

The position of the last element in the heap is changed, but `id_to_heappos` does not changed at the same time.

In some rare cases, `sift_down` will return directly without patching the  `id_to_heappos` to the correct value.

**Comment by Ten0** [comment]
Very good catches, thanks a lot and sorry for the bugs!
